# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/geoscan.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1436, 855)
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        self.lblInputFile = QtWidgets.QLabel(Dialog)
        self.lblInputFile.setGeometry(QtCore.QRect(50, 15, 541, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblInputFile.setFont(font)
        self.lblInputFile.setObjectName("lblInputFile")
        self.txtInputFile = QtWidgets.QTextBrowser(Dialog)
        self.txtInputFile.setGeometry(QtCore.QRect(40, 80, 561, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtInputFile.setFont(font)
        self.txtInputFile.setObjectName("txtInputFile")
        self.btnSelectFile = QtWidgets.QToolButton(Dialog)
        self.btnSelectFile.setGeometry(QtCore.QRect(660, 80, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnSelectFile.setFont(font)
        self.btnSelectFile.setObjectName("btnSelectFile")
        self.btnCount = QtWidgets.QPushButton(Dialog)
        self.btnCount.setGeometry(QtCore.QRect(660, 170, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnCount.setFont(font)
        self.btnCount.setObjectName("btnCount")
        self.tblPoints = QtWidgets.QTableWidget(Dialog)
        self.tblPoints.setGeometry(QtCore.QRect(40, 170, 561, 661))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tblPoints.setFont(font)
        self.tblPoints.setObjectName("tblPoints")
        self.tblPoints.setColumnCount(0)
        self.tblPoints.setRowCount(0)
        self.widget = QtWebEngineWidgets.QWebEngineView(Dialog)
        self.widget.setGeometry(QtCore.QRect(660, 230, 751, 601))
        self.widget.setObjectName("widget")
        self.comboBoxManager = QtWidgets.QComboBox(Dialog)
        self.comboBoxManager.setGeometry(QtCore.QRect(1240, 120, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBoxManager.setFont(font)
        self.comboBoxManager.setObjectName("comboBoxManager")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(1000, 120, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setLineWidth(0)
        self.label.setObjectName("label")
        self.btnBuildRoute = QtWidgets.QPushButton(Dialog)
        self.btnBuildRoute.setGeometry(QtCore.QRect(1110, 40, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnBuildRoute.setFont(font)
        self.btnBuildRoute.setObjectName("btnBuildRoute")
        self.btnDays = QtWidgets.QPushButton(Dialog)
        self.btnDays.setGeometry(QtCore.QRect(990, 170, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnDays.setFont(font)
        self.btnDays.setObjectName("btnDays")
        self.cboxDays = QtWidgets.QComboBox(Dialog)
        self.cboxDays.setGeometry(QtCore.QRect(1240, 180, 141, 31))
        self.cboxDays.setObjectName("cboxDays")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Геопланирование"))
        self.lblInputFile.setText(_translate("Dialog", "Выберите файл с входными данными в формате CSV"))
        self.btnSelectFile.setText(_translate("Dialog", "Обзор"))
        self.btnCount.setText(_translate("Dialog", "Расчет кластеров"))
        self.label.setText(_translate("Dialog", "Выберите менеджера"))
        self.btnBuildRoute.setText(_translate("Dialog", "Построить маршруты"))
        self.btnDays.setText(_translate("Dialog", "Просмотр по дням"))
from PyQt5 import QtWebEngineWidgets
